In [1]:
import numpy as np
import random
import os

n = 100
m = int(n/(2*np.log(n)+np.log(np.log(n))))

X1 = np.reshape([
    [1, 1, 1, 1, 1, 1, -1, -1, -1, -1],
[1, 1, 1, 1, 1, -1, -1, -1, -1, -1],
[1, 1, 1, 1, -1, -1, -1, -1, -1, -1],
[1, 1, 1, -1, -1, -1, -1, -1, -1, -1],
[1, 1, -1, -1, -1, -1, -1, -1, -1, -1],
[1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
], n)
X2 = np.reshape([
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
[-1, -1, -1, -1, -1, -1, -1, -1, -1, 1],
[-1, -1, -1, -1, -1, -1, -1, -1, 1, 1],
[-1, -1, -1, -1, -1, -1, -1, 1, 1, 1],
[-1, -1, -1, -1, -1, -1, 1, 1, 1, 1],
[-1, -1, -1, -1, -1, 1, 1, 1, 1, 1],
[-1, -1, -1, -1, 1, 1, 1, 1, 1, 1],
], n)
X3 = np.reshape([
[-1, -1, -1, -1, -1, -1, -1, -1, 1, 1],
[-1, -1, -1, -1, -1, -1, -1, 1, 1, 1],
[-1, -1, -1, -1, -1, -1, 1, 1, 1, -1],
[-1, -1, -1, -1, -1, 1, 1, 1, -1, -1],
[-1, -1, -1, -1, 1, 1, 1, -1, -1, -1],
[-1, -1, -1, 1, 1, 1, -1, -1, -1, -1],
[-1, -1, 1, 1, 1, -1, -1, -1, -1, -1],
[-1, 1, 1, 1, -1, -1, -1, -1, -1, -1],
[1, 1, 1, -1, -1, -1, -1, -1, -1, -1],
[1, 1, -1, -1, -1, -1, -1, -1, -1, -1],
], n)
X=[X1,X2,X3]
testX = np.reshape([
    [1, 1, 1, 1, 1, 1, -1, -1, -1, -1],
[1, 1, 1, 1, 1, -1, -1, -1, -1, -1],
[1, 1, 1, 1, -1, -1, -1, -1, -1, -1],
[1, 1, 1, -1, -1, -1, -1, -1, -1, -1],
[1, 1, -1, -1, -1, -1, -1, -1, -1, -1],
[1, -1, -1, -1, 1, -1, -1, -1, -1, -1],
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
], n)

In [2]:
def activ_fun(G):
    return np.array([1 if x > 0 else -1 for x in G])

In [3]:

W = np.zeros((n, n))
for i in range(0, n):
    for j in range(0, n):
        if i == j:
            continue
        for k in range(0, len(X)):
            W[i][j] += X[k][i] * X[k][j]    
print(W)

[[ 0.  3.  3. ... -1. -1. -1.]
 [ 3.  0.  3. ... -1. -1. -1.]
 [ 3.  3.  0. ... -1. -1. -1.]
 ...
 [-1. -1. -1. ...  0.  3.  3.]
 [-1. -1. -1. ...  3.  0.  3.]
 [-1. -1. -1. ...  3.  3.  0.]]


In [ ]:

A = np.zeros(len(testX))
while True:
    A = activ_fun(np.matmul(W, testX))
    if np.array_equal(testX, A):
        break
    tastX = A
print(A)